#!/bin/bash

#sudo apt update && sudo apt upgrade -yy
#sudo apt install torbrowser-launcher dkms build-essential vim qbittorrent vlc mpv git
sudo apt install libreadline-dev libgtk2.0-dev  libmotif-dev xfonts-75dpi xfonts-100dpi xfonts-cyrillic xfonts-base

cd ~/Documents
git clone https://github.com/radforddc/rw05
